package com.aliyun.openservices.log.functiontest;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fastLogGroup.proto

public final class FastLogGroupSer {
  private FastLogGroupSer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FastLogGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 beginOffset = 1;
    /**
     * <code>optional int32 beginOffset = 1;</code>
     */
    boolean hasBeginOffset();
    /**
     * <code>optional int32 beginOffset = 1;</code>
     */
    int getBeginOffset();

    // optional int32 endOffset = 2;
    /**
     * <code>optional int32 endOffset = 2;</code>
     */
    boolean hasEndOffset();
    /**
     * <code>optional int32 endOffset = 2;</code>
     */
    int getEndOffset();
  }
  /**
   * Protobuf type {@code FastLogGroup}
   */
  public static final class FastLogGroup extends
      com.google.protobuf.GeneratedMessage
      implements FastLogGroupOrBuilder {
    // Use FastLogGroup.newBuilder() to construct.
    private FastLogGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FastLogGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FastLogGroup defaultInstance;
    public static FastLogGroup getDefaultInstance() {
      return defaultInstance;
    }

    public FastLogGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FastLogGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              beginOffset_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              endOffset_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FastLogGroupSer.internal_static_FastLogGroup_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FastLogGroupSer.internal_static_FastLogGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FastLogGroupSer.FastLogGroup.class, FastLogGroupSer.FastLogGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<FastLogGroup> PARSER =
        new com.google.protobuf.AbstractParser<FastLogGroup>() {
      public FastLogGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FastLogGroup(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<FastLogGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 beginOffset = 1;
    public static final int BEGINOFFSET_FIELD_NUMBER = 1;
    private int beginOffset_;
    /**
     * <code>optional int32 beginOffset = 1;</code>
     */
    public boolean hasBeginOffset() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 beginOffset = 1;</code>
     */
    public int getBeginOffset() {
      return beginOffset_;
    }

    // optional int32 endOffset = 2;
    public static final int ENDOFFSET_FIELD_NUMBER = 2;
    private int endOffset_;
    /**
     * <code>optional int32 endOffset = 2;</code>
     */
    public boolean hasEndOffset() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 endOffset = 2;</code>
     */
    public int getEndOffset() {
      return endOffset_;
    }

    private void initFields() {
      beginOffset_ = 0;
      endOffset_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, beginOffset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, endOffset_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, beginOffset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, endOffset_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static FastLogGroupSer.FastLogGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static FastLogGroupSer.FastLogGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static FastLogGroupSer.FastLogGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FastLogGroupSer.FastLogGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(FastLogGroupSer.FastLogGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FastLogGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements FastLogGroupSer.FastLogGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FastLogGroupSer.internal_static_FastLogGroup_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FastLogGroupSer.internal_static_FastLogGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FastLogGroupSer.FastLogGroup.class, FastLogGroupSer.FastLogGroup.Builder.class);
      }

      // Construct using FastLogGroupSer.FastLogGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        beginOffset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        endOffset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FastLogGroupSer.internal_static_FastLogGroup_descriptor;
      }

      public FastLogGroupSer.FastLogGroup getDefaultInstanceForType() {
        return FastLogGroupSer.FastLogGroup.getDefaultInstance();
      }

      public FastLogGroupSer.FastLogGroup build() {
        FastLogGroupSer.FastLogGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FastLogGroupSer.FastLogGroup buildPartial() {
        FastLogGroupSer.FastLogGroup result = new FastLogGroupSer.FastLogGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.beginOffset_ = beginOffset_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endOffset_ = endOffset_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FastLogGroupSer.FastLogGroup) {
          return mergeFrom((FastLogGroupSer.FastLogGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FastLogGroupSer.FastLogGroup other) {
        if (other == FastLogGroupSer.FastLogGroup.getDefaultInstance()) return this;
        if (other.hasBeginOffset()) {
          setBeginOffset(other.getBeginOffset());
        }
        if (other.hasEndOffset()) {
          setEndOffset(other.getEndOffset());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FastLogGroupSer.FastLogGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FastLogGroupSer.FastLogGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 beginOffset = 1;
      private int beginOffset_ ;
      /**
       * <code>optional int32 beginOffset = 1;</code>
       */
      public boolean hasBeginOffset() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 beginOffset = 1;</code>
       */
      public int getBeginOffset() {
        return beginOffset_;
      }
      /**
       * <code>optional int32 beginOffset = 1;</code>
       */
      public Builder setBeginOffset(int value) {
        bitField0_ |= 0x00000001;
        beginOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 beginOffset = 1;</code>
       */
      public Builder clearBeginOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        beginOffset_ = 0;
        onChanged();
        return this;
      }

      // optional int32 endOffset = 2;
      private int endOffset_ ;
      /**
       * <code>optional int32 endOffset = 2;</code>
       */
      public boolean hasEndOffset() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 endOffset = 2;</code>
       */
      public int getEndOffset() {
        return endOffset_;
      }
      /**
       * <code>optional int32 endOffset = 2;</code>
       */
      public Builder setEndOffset(int value) {
        bitField0_ |= 0x00000002;
        endOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 endOffset = 2;</code>
       */
      public Builder clearEndOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endOffset_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FastLogGroup)
    }

    static {
      defaultInstance = new FastLogGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FastLogGroup)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FastLogGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FastLogGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022fastLogGroup.proto\"6\n\014FastLogGroup\022\023\n\013" +
      "beginOffset\030\001 \001(\005\022\021\n\tendOffset\030\002 \001(\005B\021B\017" +
      "FastLogGroupSer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FastLogGroup_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FastLogGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FastLogGroup_descriptor,
              new String[] { "BeginOffset", "EndOffset", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
